### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by yu2001-s** [ntuee-webprogramming/hack3-QAs#21]
(node:26628) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/yu/Documents/wp1101/hack3/backend/src/index.js:1
import mongo from "./mongo.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Module._compile (/home/yu/Documents/wp1101/hack3/backend/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .js] (/home/yu/Documents/wp1101/hack3/backend/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at Object.<anonymous> (/home/yu/Documents/wp1101/hack3/backend/node_modules/@babel/node/lib/_babel-node.js:176:21)
不知道怎麼處理

**Comment by chinyi0523** [comment]
請問有按照pre-Readme 設定babel 嗎？

**Comment by ntuee-webprogramming** [comment]
請參考 pre readme 第八點
8. 在 `hack3/backend` 內依照下面的內容執行:
```bash
// 妥善安裝 Babel 相關套件
yarn add -D @babel/cli @babel/core @babel/node @babel/preset-env

// 增加一個 .babelrc 的設定檔
{
  "presets": [
    "@babel/preset-env"
  ]
}

// 修改 package.json:
"scripts": {
    "start": "nodemon src/index.js --ext js,graphql --exec babel-node"
},
```

**Comment by yu2001-s** [comment]
有
我剛剛重設babelrc的名字就好了
好怪
